### ISSUE TITLE
tokio-runtime-worker' panicked at 'called `Result::unwrap()

### ISSUE THREAD

**Issue by bhzhu203** [nwtgck/yamux-cli-rust#75]
curl -sSN http://serller.top:5555/us1 | yamux-rust -u 127.0.0.1 4000 | curl -sSNT - http://serller.top:5555/us2
curl -sSN http://serller.top:5555/us2 | yamux-rust -ul 19999 | curl -sSNT - http://serller.top:5555/us1

[INFO] Waiting for 1 receiver(s)...
[INFO] A receiver was connected.
[INFO] Start sending to 1 receiver(s)!
[INFO] A receiver aborted.
[INFO] All receiver(s) was/were aborted halfway

```

  25:     0x7f9065550133 - <unknown>
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: WriteZero, error: "1a9742b8/1: connection is closed" }', src/main.rs:293:68
stack backtrace:
   0:     0x7f906554bd00 - <unknown>
   1:     0x7f90655810de - <unknown>
   2:     0x7f9065547bd5 - <unknown>
   3:     0x7f906554bac5 - <unknown>
   4:     0x7f906554d37f - <unknown>
   5:     0x7f906554d0ba - <unknown>
   6:     0x7f906554da78 - <unknown>
   7:     0x7f906554d817 - <unknown>
   8:     0x7f906554c1ac - <unknown>
   9:     0x7f906554d532 - <unknown>
  10:     0x7f90653f2e93 - <unknown>
  11:     0x7f90653f30f3 - <unknown>
  12:     0x7f906541b8b6 - <unknown>
  13:     0x7f90653f5bac - <unknown>
  14:     0x7f90653f7569 - <unknown>
  15:     0x7f9065526014 - <unknown>
  16:     0x7f9065511ccc - <unknown>
  17:     0x7f9065510f40 - <unknown>
  18:     0x7f90655276fe - <unknown>
  19:     0x7f9065510a9b - <unknown>
  20:     0x7f9065519b11 - <unknown>
  21:     0x7f9065521331 - <unknown>
  22:     0x7f906550cce1 - <unknown>
  23:     0x7f906551f096 - <unknown>
  24:     0x7f9065512ac8 - <unknown>
  25:     0x7f9065550133 - <unknown>
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: WriteZero, error: "1a9742b8/1: connection is closed" }', src/main.rs:293:68
stack backtrace:
   0:     0x7f906554bd00 - <unknown>
   1:     0x7f90655810de - <unknown>
   2:     0x7f9065547bd5 - <unknown>
   3:     0x7f906554bac5 - <unknown>
   4:     0x7f906554d37f - <unknown>
   5:     0x7f906554d0ba - <unknown>
   6:     0x7f906554da78 - <unknown>
   7:     0x7f906554d817 - <unknown>
   8:     0x7f906554c1ac - <unknown>
   9:     0x7f906554d532 - <unknown>
  10:     0x7f90653f2e93 - <unknown>
  11:     0x7f90653f30f3 - <unknown>
  12:     0x7f906541b8b6 - <unknown>
  13:     0x7f90653f5bac - <unknown>
  14:     0x7f90653f7569 - <unknown>
  15:     0x7f9065526014 - <unknown>
  16:     0x7f9065511ccc - <unknown>
  17:     0x7f9065510f40 - <unknown>
  18:     0x7f90655276fe - <unknown>
  19:     0x7f9065510a9b - <unknown>
  20:     0x7f9065519b11 - <unknown>
  21:     0x7f9065521331 - <unknown>
  22:     0x7f906550cce1 - <unknown>
  23:     0x7f906551f096 - <unknown>
  24:     0x7f9065512ac8 - <unknown>
  25:     0x7f9065550133 - <unknown>
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: WriteZero, error: "1a9742b8/1: connection is closed" }', src/main.rs:293:68
```

**Comment by nwtgck** [comment]
Doesn't this error occur with [yamux written in Go](https://github.com/nwtgck/yamux-cli)? Go version is recommended for now because it is faster than Rust version.
